name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Check which folder exists
        id: check_path
        run: |
          if [ -d "./dist" ]; then
            echo "path=./dist" >> $GITHUB_OUTPUT
          elif [ -d "./build" ]; then
            echo "path=./build" >> $GITHUB_OUTPUT
          else
            echo "Error: Neither dist nor build folder found."
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps: check_path.outputs.path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
